### ISSUE TITLE
Fatal error: Class 'SendyPHP' not found

### ISSUE THREAD

**Issue by ZsharE** [JacobBennett/SendyPHP#14]
Hi,

I have a problem with the API integration.
I included "SendyPHP.php" file into my index.php file, no errors, but when i call "$sendy = new SendyPHP($config);", it throws me the error : "Fatal error: Class 'SendyPHP' not found".

I really don't understand why, everything seems to be fine.

I put "SendyPHP.php" in same folder with "index.php".
Here is my index.php file:

<?php

require('SendyPHP.php');

$config = array(
        'api_key' => 'my_api_key', //your API key is available in Settings
        'installation_url' => 'my_url',  //Your Sendy installation
        'list_id' => 'my_list_id'
);

$sendy = new SendyPHP($config);

?>

Thanks in advice.

**Comment by ReessKennedy** [comment]
Yeah, we had this same issue and solved in the same way. Thanks @ZsharE.

**Comment by JacobBennett** [comment]
Updated the documentation to reflect proper include statement

Jake
