### ISSUE TITLE
Unsafe cURL settings

### ISSUE THREAD

**Issue by dominic-p** [JacobBennett/SendyPHP#19]
Hi, I just noticed some unsafe cURL settings for SSL. It looks like they were [added here](https://github.com/JacobBennett/SendyPHP/commit/f288bc0d94ee51f445213443928c927cded55597). Maybe these are just for testing, but it might be a good idea to either remove them or put a comment there so people know they aren't for production use. Looks like a nice class though. Thanks.

**Comment by JacobBennett** [comment]
Thanks for the heads up Dominic. Submit a pull request and I'll merge it
in. Thanks!

On Friday, January 2, 2015, Dominic <notifications@github.com> wrote:

> Hi, I just noticed some unsafe cURL settings for SSL. It looks like they
> were added here
> <https://github.com/JacobBennett/SendyPHP/commit/f288bc0d94ee51f445213443928c927cded55597>.
> Maybe these are just for testing, but it might be a good idea to either
> remove them or put a comment there so people know they aren't for
> production use. Looks like a nice class though. Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JacobBennett/SendyPHP/issues/19>.
>


-- 
Jake

**Comment by JacobBennett** [comment]
Your pull request was merged so this is getting closed
