### ISSUE TITLE
Composer is not loading the library

### ISSUE THREAD

**Issue by thiagolcks** [JacobBennett/SendyPHP#23]
Hi,

I'm trying to load the library with Composer but I'm getting "Fatal error: Class 'SendyPHP' not found". SendyPHP class is not in the composer/autoload_classmap.php.

Have I done something wrong?

Thanks

**Comment by JacobBennett** [comment]
@thiagolcks Guessing you figured it out? Also guessing you might not have had a `use` statement at the top of the class you were using it in, or you didn't use a compound name when instantiating it if forgoing the `use` statement? 

Let me know if is something else that I need to fix.

**Comment by thiagolcks** [comment]
Hi @JacobBennett, you hit the nail on the head. I forgot the **use** statement.
Thanks

**Comment by JacobBennett** [comment]
@thiagolcks NP
