### ISSUE TITLE
I get this

### ISSUE THREAD

**Issue by fguespe** [JacobBennett/SendyPHP#24]
Warning: require(SendyPHP\SendyPHP.php): failed to open stream: No such file or directory in /home/fguespe1/public_html/sendy.php on line 5

Fatal error: require(): Failed opening required 'SendyPHP\SendyPHP.php' (include_path='.:/opt/php5-5/lib/php') in /home/fguespe1/public_html/sendy.php on line 5

Where do i have to put it? I tried in the same folder than the file.

tried this also 

require(SendyPHP.php):

**Comment by JacobBennett** [comment]
So first off, you aren't using composer correct?

Second, you could put it in the same folder as the file you are calling it from and then just write

```
require_once('SendyPHP.php');
```

Once `SendyPHP.php` has been imported, you will need to instantiate it using

```
$config = array(
        'api_key' => 'yourapiKEYHERE', //your API key is available in Settings
        'installation_url' => 'http://updates.mydomain.com',  //Your Sendy installation
        'list_id' => 'your_list_id_goes_here'
    );
$sendy = new \SendyPHP\SendyPHP($config_array);
```

let me know if that helps
